# Generated by Django 5.2.4 on 2025-10-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_intranet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado_civil',
        ),
    ]
