# Generated by Django 5.2.7 on 2025-12-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='visibilidad_roles',
            field=models.CharField(choices=[('solo_funcionarios', 'Solo Funcionarios'), ('solo_jefatura', 'Solo Jefatura'), ('funcionarios_y_jefatura', 'Funcionarios y Jefatura'), ('solo_direccion', 'Solo Dirección y Subdirección')], default='funcionarios_y_jefatura', help_text='Determina qué roles pueden ver este anuncio. Dirección y Subdirección siempre pueden ver todos los anuncios.', max_length=30),
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['visibilidad_roles'], name='api_intrane_visibil_da81d1_idx'),
        ),
    ]
