# Generated by Django 5.2.7 on 2025-12-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_intranet', '0002_anuncio_visibilidad_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='archivo',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo_contenido',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=100),
        ),
        migrations.AddField(
            model_name='documento',
            name='nombre_archivo',
            field=models.CharField(default='documento_default.pdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='storage_type',
            field=models.CharField(choices=[('database', 'Base de Datos'), ('s3', 'Amazon S3')], default='database', max_length=20),
        ),
    ]
