# Generated by Django 5.2.7 on 2025-12-16 01:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_intranet', '0003_remove_documento_archivo_documento_archivo_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo_archivo',
            field=models.CharField(blank=True, help_text='Tipo de archivo: pdf, imagen, video, etc.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=200)),
                ('completado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['completado', '-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'completado'], name='api_intrane_usuario_6a26a4_idx')],
            },
        ),
    ]
